"""sync_supabase_changes

Revision ID: 66810908c375
Revises: 0025_create_personalized_lessons
Create Date: 2026-04-25 00:59:57.455357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66810908c375'
down_revision: Union[str, None] = '0025_create_personalized_lessons'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_event_type'), 'activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_subject'), 'activity_logs', ['subject'], unique=False)
    op.create_index(op.f('ix_activity_logs_term'), 'activity_logs', ['term'], unique=False)
    op.drop_constraint(op.f('uq_curriculum_versions_version_name'), 'curriculum_versions', type_='unique')
    op.drop_index(op.f('ix_diagnostics_scope'), table_name='diagnostics')
    op.create_index(op.f('ix_diagnostics_sss_level'), 'diagnostics', ['sss_level'], unique=False)
    op.create_index(op.f('ix_diagnostics_subject'), 'diagnostics', ['subject'], unique=False)
    op.create_index(op.f('ix_diagnostics_term'), 'diagnostics', ['term'], unique=False)
    op.drop_index(op.f('ix_internal_quiz_attempts_scope'), table_name='internal_quiz_attempts')
    op.create_index(op.f('ix_internal_quiz_attempts_sss_level'), 'internal_quiz_attempts', ['sss_level'], unique=False)
    op.create_index(op.f('ix_internal_quiz_attempts_subject'), 'internal_quiz_attempts', ['subject'], unique=False)
    op.create_index(op.f('ix_internal_quiz_attempts_term'), 'internal_quiz_attempts', ['term'], unique=False)
    op.add_column('learning_preferences', sa.Column('visual_learner', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('learning_preferences', sa.Column('practice_heavy', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('learning_preferences', sa.Column('auditory_narrations', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_index(op.f('ix_lesson_blocks_lesson'), table_name='lesson_blocks')
    op.drop_index(op.f('ix_lesson_blocks_order'), table_name='lesson_blocks')
    op.drop_index(op.f('ix_lesson_blocks_type'), table_name='lesson_blocks')
    op.create_index(op.f('ix_lesson_blocks_block_type'), 'lesson_blocks', ['block_type'], unique=False)
    op.create_index(op.f('ix_lesson_blocks_lesson_id'), 'lesson_blocks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_blocks_order_index'), 'lesson_blocks', ['order_index'], unique=False)
    op.drop_index(op.f('ix_lessons_topic'), table_name='lessons')
    op.create_index(op.f('ix_lessons_topic_id'), 'lessons', ['topic_id'], unique=False)
    op.drop_index(op.f('ix_mastery_update_events_created_at'), table_name='mastery_update_events')
    op.create_index(op.f('ix_mastery_update_events_attempt_id'), 'mastery_update_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_mastery_update_events_quiz_id'), 'mastery_update_events', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_mastery_update_events_sss_level'), 'mastery_update_events', ['sss_level'], unique=False)
    op.create_index(op.f('ix_mastery_update_events_subject'), 'mastery_update_events', ['subject'], unique=False)
    op.create_index(op.f('ix_mastery_update_events_term'), 'mastery_update_events', ['term'], unique=False)
    op.drop_constraint(op.f('uq_quiz_answers_attempt_id_question_id'), 'quiz_answers', type_='unique')
    op.drop_column('quiz_attempts', 'submitted_at')
    op.drop_constraint(op.f('uq_quiz_questions_quiz_id_question_number'), 'quiz_questions', type_='unique')
    op.drop_index(op.f('ix_quizzes_scope'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_status'), table_name='quizzes')
    op.create_index(op.f('ix_quizzes_sss_level'), 'quizzes', ['sss_level'], unique=False)
    op.create_index(op.f('ix_quizzes_subject'), 'quizzes', ['subject'], unique=False)
    op.create_index(op.f('ix_quizzes_term'), 'quizzes', ['term'], unique=False)
    op.drop_index(op.f('ix_student_concept_mastery_scope'), table_name='student_concept_mastery')
    op.create_index(op.f('ix_student_concept_mastery_sss_level'), 'student_concept_mastery', ['sss_level'], unique=False)
    op.create_index(op.f('ix_student_concept_mastery_subject'), 'student_concept_mastery', ['subject'], unique=False)
    op.create_index(op.f('ix_student_concept_mastery_term'), 'student_concept_mastery', ['term'], unique=False)
    op.create_index(op.f('ix_student_profiles_active_term'), 'student_profiles', ['active_term'], unique=False)
    op.create_index(op.f('ix_student_profiles_sss_level'), 'student_profiles', ['sss_level'], unique=False)
    op.drop_index(op.f('ix_student_subjects_profile'), table_name='student_subjects')
    op.drop_index(op.f('ix_student_subjects_subject'), table_name='student_subjects')
    op.drop_constraint(op.f('uq_student_subject'), 'student_subjects', type_='unique')
    op.create_unique_constraint('uq_student_profile_subject', 'student_subjects', ['student_profile_id', 'subject_id'])
    op.drop_index(op.f('ix_teacher_assignments_type'), table_name='teacher_assignments')
    op.create_index(op.f('ix_teacher_assignments_assignment_type'), 'teacher_assignments', ['assignment_type'], unique=False)
    op.drop_index(op.f('ix_teacher_interventions_type'), table_name='teacher_interventions')
    op.create_index(op.f('ix_teacher_interventions_intervention_type'), 'teacher_interventions', ['intervention_type'], unique=False)
    op.drop_index(op.f('ix_topics_approved'), table_name='topics')
    op.drop_index(op.f('ix_topics_scope'), table_name='topics')
    op.drop_index(op.f('ix_topics_subject'), table_name='topics')
    op.create_index(op.f('ix_topics_curriculum_version_id'), 'topics', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_topics_is_approved'), 'topics', ['is_approved'], unique=False)
    op.create_index(op.f('ix_topics_sss_level'), 'topics', ['sss_level'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_index(op.f('ix_topics_term'), 'topics', ['term'], unique=False)
    op.drop_constraint(op.f('fk_topics_curriculum_version_id'), 'topics', type_='foreignkey')
    op.drop_index(op.f('ix_tutor_messages_created_at'), table_name='tutor_messages')
    op.drop_index(op.f('ix_tutor_sessions_scope'), table_name='tutor_sessions')
    op.drop_index(op.f('ix_tutor_sessions_status'), table_name='tutor_sessions')
    op.create_index(op.f('ix_tutor_sessions_subject'), 'tutor_sessions', ['subject'], unique=False)
    op.create_index(op.f('ix_tutor_sessions_term'), 'tutor_sessions', ['term'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_sessions_term'), table_name='tutor_sessions')
    op.drop_index(op.f('ix_tutor_sessions_subject'), table_name='tutor_sessions')
    op.create_index(op.f('ix_tutor_sessions_status'), 'tutor_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_tutor_sessions_scope'), 'tutor_sessions', ['subject', 'term'], unique=False)
    op.create_index(op.f('ix_tutor_messages_created_at'), 'tutor_messages', ['created_at'], unique=False)
    op.create_foreign_key(op.f('fk_topics_curriculum_version_id'), 'topics', 'curriculum_versions', ['curriculum_version_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_topics_term'), table_name='topics')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_sss_level'), table_name='topics')
    op.drop_index(op.f('ix_topics_is_approved'), table_name='topics')
    op.drop_index(op.f('ix_topics_curriculum_version_id'), table_name='topics')
    op.create_index(op.f('ix_topics_subject'), 'topics', ['subject_id'], unique=False)
    op.create_index(op.f('ix_topics_scope'), 'topics', ['sss_level', 'term'], unique=False)
    op.create_index(op.f('ix_topics_approved'), 'topics', ['is_approved'], unique=False)
    op.drop_index(op.f('ix_teacher_interventions_intervention_type'), table_name='teacher_interventions')
    op.create_index(op.f('ix_teacher_interventions_type'), 'teacher_interventions', ['intervention_type'], unique=False)
    op.drop_index(op.f('ix_teacher_assignments_assignment_type'), table_name='teacher_assignments')
    op.create_index(op.f('ix_teacher_assignments_type'), 'teacher_assignments', ['assignment_type'], unique=False)
    op.drop_constraint('uq_student_profile_subject', 'student_subjects', type_='unique')
    op.create_unique_constraint(op.f('uq_student_subject'), 'student_subjects', ['student_profile_id', 'subject_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_student_subjects_subject'), 'student_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_student_subjects_profile'), 'student_subjects', ['student_profile_id'], unique=False)
    op.drop_index(op.f('ix_student_profiles_sss_level'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_active_term'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_concept_mastery_term'), table_name='student_concept_mastery')
    op.drop_index(op.f('ix_student_concept_mastery_subject'), table_name='student_concept_mastery')
    op.drop_index(op.f('ix_student_concept_mastery_sss_level'), table_name='student_concept_mastery')
    op.create_index(op.f('ix_student_concept_mastery_scope'), 'student_concept_mastery', ['subject', 'sss_level', 'term'], unique=False)
    op.drop_index(op.f('ix_quizzes_term'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_subject'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_sss_level'), table_name='quizzes')
    op.create_index(op.f('ix_quizzes_status'), 'quizzes', ['status'], unique=False)
    op.create_index(op.f('ix_quizzes_scope'), 'quizzes', ['subject', 'sss_level', 'term'], unique=False)
    op.create_unique_constraint(op.f('uq_quiz_questions_quiz_id_question_number'), 'quiz_questions', ['quiz_id', 'question_number'], postgresql_nulls_not_distinct=False)
    op.add_column('quiz_attempts', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_quiz_answers_attempt_id_question_id'), 'quiz_answers', ['attempt_id', 'question_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_mastery_update_events_term'), table_name='mastery_update_events')
    op.drop_index(op.f('ix_mastery_update_events_subject'), table_name='mastery_update_events')
    op.drop_index(op.f('ix_mastery_update_events_sss_level'), table_name='mastery_update_events')
    op.drop_index(op.f('ix_mastery_update_events_quiz_id'), table_name='mastery_update_events')
    op.drop_index(op.f('ix_mastery_update_events_attempt_id'), table_name='mastery_update_events')
    op.create_index(op.f('ix_mastery_update_events_created_at'), 'mastery_update_events', ['created_at'], unique=False)
    op.drop_index(op.f('ix_lessons_topic_id'), table_name='lessons')
    op.create_index(op.f('ix_lessons_topic'), 'lessons', ['topic_id'], unique=False)
    op.drop_index(op.f('ix_lesson_blocks_order_index'), table_name='lesson_blocks')
    op.drop_index(op.f('ix_lesson_blocks_lesson_id'), table_name='lesson_blocks')
    op.drop_index(op.f('ix_lesson_blocks_block_type'), table_name='lesson_blocks')
    op.create_index(op.f('ix_lesson_blocks_type'), 'lesson_blocks', ['block_type'], unique=False)
    op.create_index(op.f('ix_lesson_blocks_order'), 'lesson_blocks', ['lesson_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_lesson_blocks_lesson'), 'lesson_blocks', ['lesson_id'], unique=False)
    op.alter_column('learning_preferences', 'auditory_narrations',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('learning_preferences', 'practice_heavy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('learning_preferences', 'visual_learner',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_internal_quiz_attempts_term'), table_name='internal_quiz_attempts')
    op.drop_index(op.f('ix_internal_quiz_attempts_subject'), table_name='internal_quiz_attempts')
    op.drop_index(op.f('ix_internal_quiz_attempts_sss_level'), table_name='internal_quiz_attempts')
    op.create_index(op.f('ix_internal_quiz_attempts_scope'), 'internal_quiz_attempts', ['subject', 'sss_level', 'term'], unique=False)
    op.drop_index(op.f('ix_diagnostics_term'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_subject'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_sss_level'), table_name='diagnostics')
    op.create_index(op.f('ix_diagnostics_scope'), 'diagnostics', ['subject', 'sss_level', 'term'], unique=False)
    op.create_unique_constraint(op.f('uq_curriculum_versions_version_name'), 'curriculum_versions', ['version_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_activity_logs_term'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_subject'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_event_type'), table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###